image: bilby91/ddsl:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind
stages:
  - build
  - checks
  - publish
before_script:
  - export CI_SHA1=gitlab-$CI_COMMIT_SHA
build:
  stage: build
  script:
    - ddsl build feature-branch
  except:
    - master
build-master:
  stage: build
  script:
    - ddsl build master-branch
  only:
    - master
test:
  stage: checks
  script:
    - ddsl run test-ci
lint:
  stage: checks
  script:
    - ddsl run lint-ci
publish:
  stage: publish
  script:
    - ddsl run publish
  only:
    - /v[0-9]+(\.[0-9]+)*/