version: '3'

volumes:
  ddsl_bundle:

services:
  dind:
    image: docker:dind
    privileged: true
  ddsl:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    environment:
      BUNDLE_PATH: /bundle
      DOCKER_HOST: tcp://dind:2375
    volumes:
      - ../:/var/www/app:cached
      - ddsl_bundle:/bundle:cached
      - ~/.bash_history:/root/.bash_history
      - /Users/bilby91/Projects/github.com/json_schemer:/var/www/json_schemer
    depends_on:
      - dind