FROM docker:18.05

LABEL maintainer="Martín Fernández <fmartin91@gmail.com>"

# Application directory
ENV APP_HOME /var/www/app

# Configure gems path
ENV BUNDLE_PATH /bundle

# Install the base tooling
RUN apk add --no-cache \
      build-base \
      gcc \
      python \
      py-pip \
      python-dev \
      gettext \
      curl \
      bash \
      git \
      ruby \
      ruby-dev \
      ruby-bigdecimal 

# Install untrusted packages (separate line for scoping)
RUN apk add --no-cache \
    --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
    --allow-untrusted \
    aws-cli

# Install docker-compose
RUN pip install docker-compose

# Install ruby dependencies
RUN gem install builder bundler --no-ri

WORKDIR ${APP_HOME}